name: Metrics
on:
  # Update setiap jam 00:00 WIB
  schedule: [{cron: "0 17 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ghinayantes
          template: classic
          
          # --- BAGIAN PENTING: PENGATURAN TAMPILAN ---
          
          # 1. Base: Cuma ambil Header (Stats ringkas) 
          # (Ini pengganti gambar stats yang pecah tadi)
          base: header
          
          # 2. Kalender 3D (Yang kamu suka)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # 3. Grafik Bahasa (Biar berwarna)
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          
          # Hapus bagian 'activity', 'community', dll biar ga penuh teks
          config_timezone: Asia/Jakarta
