name: Metrics
on:
  # Update setiap jam 00:00 WIB
  schedule: [{cron: "0 17 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Identitas Kamu
          user: ghinayantes
          template: classic
          
          # FITUR 1: Grafik Dasar (Activity Overview)
          base: header, activity, community, repositories, metadata
          
          # FITUR 2: Grafik Koordinat/Jaring (Bahasa Pemrograman)
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_recent_categories: markup, programming
          
          # FITUR 3: Kalender 3D (Kotak-kotak Timbul Keren)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          config_timezone: Asia/Jakarta
